# deploy-public-key.yaml
---
- name: Get the public key from localhost
  hosts: localhost
  tasks:
    - name: Read public key into variable/fact
      ansible.builtin.set_fact:
        public_key: "{{ lookup('file', ansible_env.HOME + '/.ssh/id_rsa_rpi.pub') }}"

- name: Deploy the public key to remote hosts
  gather_facts: no
  hosts: all
  tasks:
    - name: Put public key in place
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ hostvars.localhost.public_key }}"

    - name: Disable Password Authentication on all nodes
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#PasswordAuthentication yes$"
        line: "PasswordAuthentication no"
      notify:
        - Restart SSH daemon

  handlers:
    - name: Restart SSH daemon
      become: true
      ansible.builtin.systemd:
        name: ssh
        daemon_reload: yes
        state: restarted
