# initialise.yaml
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#initializing-your-control-plane-node
---
- name: Initialise the control-plane node
  become: true
  gather_facts: no
  hosts: main
  tasks:
    - name: Run 'kubeadm init' on the control-plane node
      ansible.builtin.command: kubeadm init
      register: kubeadm_init
      changed_when: false
      tags: [cp_only]

    - name: Run regexes and set 'kubeadm join' command as fact
      ansible.builtin.set_fact:
        kubeadm_join: "{{ kubeadm_init.stdout | regex_search(regexp,'\\1') | regex_replace(' \\\\+n +', ' ') }}"
      vars:
        regexp: "(?is)(kubeadm join .*)"

- name: Install a Pod network add-on
  become: true
  gather_facts: no
  hosts: main
  tasks:
    - name: Get Calico manifest
      ansible.builtin.get_url:
        url: https://docs.projectcalico.org/manifests/calico.yaml
        dest: /tmp/calico.yaml

    - name: Install openshift Python package
      ansible.builtin.pip:
        name: openshift

    - name: Apply Calico manifest to the cluster
      community.kubernetes.k8s:
        src: /tmp/calico.yaml
        state: present
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    # vvv - TODO: candidate for removal; keep an eye on the GH issue - vvv

    - name: Patch to resolve iptables issue - https://github.com/projectcalico/calico/issues/4487
      community.kubernetes.k8s:
        state: present
        resource_definition:
          apiVersion: crd.projectcalico.org/v1
          kind: FelixConfiguration
          metadata:
            name: default
            namespace: default
          spec:
            iptablesBackend: Legacy
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    # ^^^ - TODO: candidate for removal; keep an eye on the GH issue - ^^^

- name: Join worker nodes to cluster
  become: true
  gather_facts: no
  hosts: workers
  tasks:
    - name: Run 'kubeadm join' on workers
      ansible.builtin.command: "{{ hostvars['main']['kubeadm_join'][0] }}"

- name: De-taint control plane
  become: true
  gather_facts: no
  hosts: main
  tasks:
    - name: De-taint control plane
      ansible.builtin.command: kubectl taint nodes --all node-role.kubernetes.io/master-
      changed_when: false
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

- name: Retrieve kubeconfig to local
  become: true
  hosts: main
  tags: [cp_only]
  tasks:
    - name: Set temporary kubeconfig filename as fact
      ansible.builtin.set_fact:
        kubeconfig_filename: "/tmp/rpi-kubeconfig.{{ ansible_date_time.iso8601 }}.yaml"

    - name: Generate kubectl credential from main
      ansible.builtin.shell: >-
        kubeadm alpha kubeconfig user
        --client-name=jltykmbp --config=
        >>
        "{{ kubeconfig_filename }}"

    - name: Fetch kubeconfig from CP into local file
      ansible.builtin.fetch:
        src: "{{ kubeconfig_filename }}"
        dest: "{{ kubeconfig_filename }}"

    - name: Clean up temporary kubeconfig file
      ansible.builtin.file:
        path: "{{ kubeconfig_filename }}"
        state: absent

- name: Fold new kubeconfig into local
  # TODO: try slurping instead
  hosts: localhost
  tasks:
    - name: Set local kubeconfig filename fact, based on copy from remote
      ansible.builtin.set_fact:
        kubeconfig_filename: "{{ path_components | join('/') }}"
      vars:
        path_components:
          - "{{ hostvars['main']['kubeconfig_filename'] }}"
          - "main"
          - "{{ hostvars['main']['kubeconfig_filename'] }}"

    - name: Extract the data from the YAML file into a fact
      ansible.builtin.set_fact:
        original_kubeconfig: "{{ lookup('file', kubeconfig_filename) | from_yaml }}"

    - name: Clean up temporary kubeconfig file
      ansible.builtin.file:
        path: "{{ hostvars['main']['kubeconfig_filename'] }}"
        state: absent

    - name: Update the fact
      ansible.utils.update_fact:
        updates:
          - path: original_kubeconfig.clusters[0].name
            value: rpi
          - path: original_kubeconfig.contexts[0].context.cluster
            value: rpi
          - path: original_kubeconfig.contexts[0].name
            value: jltykmbp@rpi
          - path: original_kubeconfig.current-context
            value: jltykmbp@rpi
      register: updated_kubeconfig

    - name: Set updated kubeconfig file path as a fact
      ansible.builtin.set_fact:
        updated_kubeconfig_file: "/tmp/kubeconfig.{{ ansible_date_time.iso8601 }}.yaml"

    - name: Write updated kubeconfig fact back to a YAML file
      ansible.builtin.copy:
        content: "{{ updated_kubeconfig.original_kubeconfig | to_nice_yaml }}"
        dest: "{{ updated_kubeconfig_file }}"
        mode: 0400

    - name: Set merged kubeconfig file path as a fact
      ansible.builtin.set_fact:
        merged_kubeconfig_file: "/tmp/kubeconfig.merged.{{ ansible_date_time.iso8601 }}.yaml"

    # https://github.com/mikefarah/yq/issues/774#issuecomment-819929091
    - name: Merge with my current kubeconfig
      ansible.builtin.shell: >-
        yq eval-all '. as $item ireduce ({}; . *d $item )'
        "{{ ansible_env.HOME }}/.kube/config"
        "{{ updated_kubeconfig_file }}"
        >>
        "{{ merged_kubeconfig_file }}"

    - name: Clean up temporary merged kubeconfig file
      ansible.builtin.file:
        path: "{{ updated_kubeconfig_file }}"
        state: absent

    - name: Move current kubeconfig out of the way, to keep a backup
      ansible.builtin.command: >-
        mv
        {{ ansible_env.HOME }}/.kube/config
        {{ ansible_env.HOME }}/.kube/config.{{ ansible_date_time.iso8601 }}

    - name: Move updated/merged kubeconfig into place
      ansible.builtin.command: >-
        mv
        {{ merged_kubeconfig_file }}
        {{ ansible_env.HOME }}/.kube/config

    - name: Set mode on kubeconfig
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.kube/config"
        mode: 0600
