# k8s-maintenance.yaml
---
- name: Prepare to upgrade a node in a Kubernetes cluster
  become: true
  hosts: raspberry_pi
  serial: 1

  tasks:
    - name: Take kubeadm off hold
      dpkg_selections:
        name: kubeadm
        selection: install

    # 2021-05-08:
    # https://github.com/kubernetes/kubernetes/releases/latest
    # $ sudo apt update && apt-cache madison kubeadm | head
    # NOTE: we target the second-highest minor version
    - name: Upgrade kubeadm to v1.20.6
      apt:
        name: kubeadm=1.20.6-00
        state: present
        update_cache: true

    - name: Put kubeadm back on hold
      dpkg_selections:
        name: kubeadm
        selection: hold

    - name: Pull images for imminent upgrade
      register: image_pull
      command:
        argv:
          - kubeadm
          - config
          - images
          - pull
      changed_when:
        - '"[config/images] Pulled" in image_pull.stdout'
