# TOML config file for SeaweedFS filer store.
#
# Put this file to one of these locations, with descending priority:
#  - ./filer.toml
#  - $HOME/.seaweedfs/filer.toml
#  - /etc/seaweedfs/filer.toml
#
# Used with "weed filer" or "weed server -filer".

####################################################
# Customizable filer server options
####################################################
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = false

####################################################
# The following are filer store options
####################################################

[leveldb2]
# local on disk, mostly for simple single-machine setup, fairly scalable
# faster than previous leveldb, recommended.
dir = "/var/lib/seaweedfs/filer-leveldb2" # directory to store level db files
enabled = true
