# update-kube-packages.yaml
# Prepare to upgrade nodes in the Kubernetes cluster
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#installing-kubeadm-on-your-hosts
---
- name: Update kube packages on all nodes in the cluster
  become: true
  gather_facts: no
  hosts: all
  tasks:
    - name: Take packages off hold
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: install
      loop:
        - kubeadm
        - kubectl
        - kubelet

    # 2021-05-20:
    # https://github.com/kubernetes/kubernetes/releases/latest
    # $ sudo apt update && apt-cache madison kubeadm | head
    # NOTE: we target the second-highest minor version
    - name: Upgrade packages to v1.20.7
      ansible.builtin.apt:
        name:
          - kubeadm=1.20.7-00
          - kubectl=1.20.7-00
          - kubelet=1.20.7-00
        state: present
        update_cache: true

    - name: Put packages back on hold
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubeadm
        - kubectl
        - kubelet

- name: Pull images for imminent upgrade, one node at a time
  serial: 1
  become: true
  gather_facts: no
  hosts: all
  tasks:
    - name: Pull images for imminent upgrade
      ansible.builtin.command: kubeadm config images pull
      register: image_pull
      changed_when: '"[config/images] Pulled" in image_pull.stdout'
