# /etc/seaweedfs/mount.conf

# Local cache directory for file chunks and meta data.
cacheDir=/var/cache/seaweedfs

# Mount weed filer to this directory.
dir=/mnt/weed

# Auto create the directory to mount to.
dirAutoCreate=true

# Comma-separated weed filer location.
filer=localhost:8888
