---
# tasks file for roles/webservers
- name: Upload application file
  ansible.builtin.copy:
    src: files/index.php
    dest: '{{ webservers_path_to_app }}'
    mode: '0o755'

- name: Remove default HTML file
  ansible.builtin.file:
    path: '{{ webservers_path_to_app }}/index.html'
    state: absent

- name: Create simple info page
  ansible.builtin.copy:
    dest: '{{ webservers_path_to_app }}/info.php'
    content: '<h1>Info about our webserver: {{ ansible_hostname }}</h1>'
    mode: '0o640'

- name: See directory contents
  ansible.builtin.command: ls -la {{ webservers_path_to_app }}
  register: webservers_dir_contents
  changed_when: false

- name: Debug directory contents
  ansible.builtin.debug:
    msg: '{{ webservers_dir_contents }}'

- name: Configure php.ini file
  ansible.builtin.lineinfile:
    path: /etc/php/7.3/apache2/php.ini
    regexp: ^short_open_tag
    line: short_open_tag = On
  notify: Restart Apache
