# pi-cluster.yaml
---
- name: Run pre-tasks and tasks for Pi cluster
  hosts: localhost
  connection: local
  gather_facts: true
  pre_tasks:
    - name: Loading common tasks
      ansible.builtin.include_tasks: common/main.yaml
  tasks:
    - name: Run main playbook
      ansible.builtin.include_tasks: run/main.yaml
