# all-playbooks.yaml
---
- name: Install services
  import_playbook: install-services.yaml

- name: Setup app
  import_playbook: setup-app.yaml

- name: Setup LB
  import_playbook: setup-lb.yaml

- name: Check status
  import_playbook: check-status.yaml
