# check-status.yaml
---
- name: Check status
  hosts: webservers:loadbalancers
  tasks:
    # noqa: command-instead-of-module inline-env-var # Demonstration purposes.
    - name: Check status of Apache (using 'command')
      become: true
      ansible.builtin.command: service apache2 status
      args:
        warn: false
      changed_when: false

    # noqa: ignore-errors # Demonstration purposes.
    - name: This will not fail
      ansible.builtin.command: /bin/false
      ignore_errors: true
      changed_when: false

    - name: Gather facts about services
      ansible.builtin.service_facts: {}

    - name: Check status of Apache (using 'service_facts')
      ansible.builtin.debug:
        msg: >-
          {{ ansible_facts.services['apache2.service']['name'] }} /
          {{ ansible_facts.services['apache2.service']['source'] }} /
          {{ ansible_facts.services['apache2.service']['state'] }} /
          {{ ansible_facts.services['apache2.service']['status'] }}
