# cleanup.yaml
---
- name: Load balancers
  hosts: loadbalancers
  become: true
  tasks:
    - name: Remove Apache package from load balancer
      ansible.builtin.apt:
        name: apache2
        state: absent

- name: Web servers
  hosts: webservers
  become: true
  tasks:
    - name: Remove services from web servers
      ansible.builtin.apt:
        name:
          - apache2
          - php7.3
        state: absent

    - name: Clean up PHP config files
      ansible.builtin.file:
        path: /etc/php
        state: absent

    - name: Clean up web files
      ansible.builtin.file:
        path: /var/www
        state: absent

- name: Load balancers and web servers
  hosts: loadbalancers:webservers
  become: true
  tasks:
    - name: Shut off Apache service
      ansible.builtin.service:
        name: apache2
        enabled: false
        state: stopped

    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true

    - name: Clean up Apache config files
      ansible.builtin.file:
        path: /etc/apache2
        state: absent
