# setup-lb.yaml
---
- name: Set up load balancers
  hosts: loadbalancers
  become: true
  tasks:
    - name: Create Apache load balancer configuration from Jinja template
      ansible.builtin.template:
        src: ../config/lb-config.j2
        dest: /etc/apache2/conf-available/lb.conf
        owner: root
        group: root
        mode: '0o640'

    - name: Enable Apache load balancer configuration
      ansible.builtin.command:
        cmd: a2enconf lb
        creates: /etc/apache2/conf-enabled/lb.conf
      register: a2enconf
      notify: Restart Apache

    - name: Enable the Apache module lbmethod_byrequests
      community.general.apache2_module:
        state: present
        name: lbmethod_byrequests
      notify: Restart Apache

    - name: Enable the Apache module proxy_http
      community.general.apache2_module:
        state: present
        name: proxy_http
      notify: Restart Apache

    - name: Debug a2enconf stdout
      ansible.builtin.debug:
        var: a2enconf.stdout_lines

  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
