# setup-app.yaml
---
- hosts: webservers
  become: true
  tasks:
    - name: Upload application file
      copy:
        src: ../index.php
        dest: /var/www/html
        mode: 0755

    - name: Remove default HTML file
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Configure php.ini file
      lineinfile:
        path: /etc/php/7.3/apache2/php.ini
        regexp: ^short_open_tag
        line: "short_open_tag = On"

    - name: Restart apache
      service:
        name: apache2
        state: restarted
