---
name: Ansible playbook syntax check

on: # yamllint disable-line rule:truthy
  push:
    paths:
      - .github/workflows/syntax-check.yaml
      - playbooks/**

permissions: {}

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  syntax-check:
    name: Syntax check

    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0

      - run: pip install ansible

      - run: ansible-playbook --syntax-check playbooks/*.yaml
