---
on: push # yamllint disable-line rule:truthy

defaults:
  run:
    shell: bash

jobs:
  yamllint:
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - run: pip install yamllint

      - run: yamllint --strict .
